source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DKCompoundOperation_Example', :exclusive => true do
  pod "DKCompoundOperation", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DKCompoundOperation", :path => "../"

  
end
